# Generated by Django 5.2.8 on 2025-11-06 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_cache', models.CharField(blank=True, default='', max_length=150)),
                ('action', models.CharField(choices=[('CREATE_INVOICE', 'Create Invoice'), ('UPDATE_INVOICE', 'Update Invoice'), ('DELETE_INVOICE', 'Delete Invoice'), ('CHANGE_STATUS', 'Change Invoice Status'), ('CREATE_REMARK', 'Create Invoice Remark'), ('DELETE_REMARK', 'Delete Invoice Remark'), ('REORDER_REMARK', 'Reorder Invoice Remark')], max_length=32)),
                ('entity_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('REMARK', 'Invoice Remark')], max_length=16)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('entity_label', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='log_logentr_created_7b0d6e_idx'), models.Index(fields=['action'], name='log_logentr_action_031d57_idx'), models.Index(fields=['entity_type'], name='log_logentr_entity__8d99af_idx')],
            },
        ),
    ]
