# Generated by Django 5.2.7 on 2025-11-05 14:08

import dashboard.models
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceRemarkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_remark_name_ci')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('invoice_number', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(choices=[('IDR', 'IDR'), ('USD', 'USD'), ('SGD', 'SGD')], default='IDR', max_length=3)),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Progress', 'Progress'), ('Paid', 'Paid')], default='Unpaid', max_length=10)),
                ('from_party', models.CharField(max_length=200)),
                ('to_party', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=dashboard.models.invoice_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('remark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.invoiceremarkcategory')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
