# Generated by Django 5.2.7 on 2025-11-05 14:10

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=dashboard.models.invoice_upload_path),
        ),
    ]
