# Generated by Django 5.2.8 on 2025-11-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_invoice_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Progress', 'Progress'), ('Paid by MIMS Recoverable', 'Paid by MIMS Recoverable'), ('Paid by MIMS Expense', 'Paid by MIMS Expense'), ('Paid by Fund', 'Paid by Fund')], default='Unpaid', max_length=60),
        ),
    ]
